import { createStore } from '../lib/store';
import {
  getGitDiff,
  getGitLog,
  getGitBranches,
  getGitSummary,
  getGitPullRequest,
  stageGitFiles,
  unstageGitFiles,
  commitGit,
  checkoutGitBranch,
  pullGit,
  pushGit,
  createGitPullRequest,
  generateCommitMessage as generateCommitMessageApi,
} from '../lib/api';
import type {
  GitStatusResponse,
  GitDiffResponse,
  GitLogResponse,
  GitBranchesResponse,
  GitPullRequestResponse,
  GitSummaryResponse,
} from '../lib/api/git';

export interface GitState {
  repoPath: string | null;
  loading: boolean;
  error: string | null;
  status: GitStatusResponse | null;
  diff: GitDiffResponse | null;
  log: GitLogResponse | null;
  branches: GitBranchesResponse | null;
  summary: GitSummaryResponse | null;
  pullRequest: GitPullRequestResponse | null;
  commitMessage: string;
  /** Whether a commit message is being generated by AI */
  generating: boolean;
  /** Which model produced the generated message (shown to user) */
  generatedBy: string | null;
  /** Error message from last failed generate attempt */
  generateError: string | null;
  /** Error code from last failed generate attempt */
  generateErrorCode: string | null;
  committing: boolean;
  staging: boolean;
  syncing: boolean;
  switchingBranch: boolean;
  creatingPullRequest: boolean;
  diffView: 'unstaged' | 'staged';
  selectedBranch: string;
  newBranchName: string;
  pullRequestTitle: string;
  pullRequestBody: string;
  checkResults: import('../lib/api/git').GitCheckResults | null;
  checkFailed: boolean;
  unsafeOverrideReason: string;
  showOverrideInput: boolean;
  sections: Record<GitReadSection, GitReadSectionState>;
}

export type GitReadSection = 'summary' | 'log' | 'branches';

export interface GitReadSectionState {
  loading: boolean;
  error: string | null;
  updatedAt: string | null;
}

const EMPTY_READ_SECTION: GitReadSectionState = {
  loading: false,
  error: null,
  updatedAt: null,
};

function createReadSections(): GitState['sections'] {
  return {
    summary: { ...EMPTY_READ_SECTION },
    log: { ...EMPTY_READ_SECTION },
    branches: { ...EMPTY_READ_SECTION },
  };
}

const INITIAL_STATE: GitState = {
  repoPath: null,
  loading: false,
  error: null,
  status: null,
  diff: null,
  log: null,
  branches: null,
  summary: null,
  pullRequest: null,
  commitMessage: '',
  generating: false,
  generatedBy: null,
  generateError: null,
  generateErrorCode: null,
  committing: false,
  staging: false,
  syncing: false,
  switchingBranch: false,
  creatingPullRequest: false,
  diffView: 'unstaged',
  selectedBranch: '',
  newBranchName: '',
  pullRequestTitle: '',
  pullRequestBody: '',
  checkResults: null,
  checkFailed: false,
  unsafeOverrideReason: '',
  showOverrideInput: false,
  sections: createReadSections(),
};

function createGitStore() {
  const store = createStore<GitState>(INITIAL_STATE);
  let requestVersion = 0;

  async function loadRepoState(repoPath: string): Promise<void> {
    const nextVersion = ++requestVersion;
    store.setState((s) => {
      const repoChanged = s.repoPath !== repoPath;
      const sections = createReadSections();
      for (const section of Object.keys(sections) as GitReadSection[]) sections[section].loading = true;
      return {
        ...s,
        repoPath,
        loading: true,
        error: null,
        status: repoChanged ? null : s.status,
        log: repoChanged ? null : s.log,
        branches: repoChanged ? null : s.branches,
        summary: repoChanged ? null : s.summary,
        pullRequest: repoChanged ? null : s.pullRequest,
        selectedBranch: repoChanged ? '' : s.selectedBranch,
        sections,
      };
    });

    const publishFailure = (section: GitReadSection, error: unknown) => {
      if (nextVersion !== requestVersion) return;
      store.setState((s) => ({
        ...s,
        sections: {
          ...s.sections,
          [section]: {
            ...s.sections[section],
            loading: false,
            error: error instanceof Error ? error.message : String(error),
          },
        },
      }));
    };

    const summaryRequest = getGitSummary(repoPath).then((summary) => {
      if (nextVersion !== requestVersion) return;
      const status: GitStatusResponse = {
        branch: summary.branch || undefined as unknown as string,
        files: summary.files,
        clean: summary.clean,
        stagedCount: summary.stagedFiles,
        unstagedCount: summary.changedFiles - summary.stagedFiles,
        ahead: summary.ahead,
        behind: summary.behind,
        upstream: summary.upstream,
        remoteName: summary.remoteName,
      };
      store.setState((s) => ({
        ...s,
        status,
        summary,
        pullRequest: summary.pullRequest
          ? { available: true, tool: 'gh' as const, authenticated: true, pullRequest: summary.pullRequest }
          : null,
        selectedBranch: summary.branch || s.selectedBranch,
        sections: {
          ...s.sections,
          summary: { loading: false, error: null, updatedAt: new Date().toISOString() },
        },
      }));
    }).catch((error) => {
      publishFailure('summary', error);
      throw error;
    });

    const logRequest = getGitLog(repoPath).then((log) => {
      if (nextVersion !== requestVersion) return;
      store.setState((s) => ({
        ...s,
        log,
        sections: {
          ...s.sections,
          log: { loading: false, error: null, updatedAt: new Date().toISOString() },
        },
      }));
    }).catch((error) => {
      publishFailure('log', error);
      throw error;
    });

    const branchesRequest = getGitBranches(repoPath).then((branches) => {
      if (nextVersion !== requestVersion) return;
      store.setState((s) => ({
        ...s,
        branches,
        selectedBranch: s.selectedBranch || branches.currentBranch || '',
        sections: {
          ...s.sections,
          branches: { loading: false, error: null, updatedAt: new Date().toISOString() },
        },
      }));
    }).catch((error) => {
      publishFailure('branches', error);
      throw error;
    });

    await Promise.allSettled([summaryRequest, logRequest, branchesRequest]);
    if (nextVersion !== requestVersion) return;
    store.setState((s) => ({
      ...s,
      loading: false,
      error: (Object.values(s.sections) as GitReadSectionState[])
        .map((section) => section.error)
        .filter((value): value is string => Boolean(value))
        .join('; ') || null,
    }));
  }

  async function loadStatus(repoPath: string): Promise<void> {
    await loadRepoState(repoPath);
  }

  async function loadDiff(): Promise<void> {
    const { repoPath, diffView } = store.getState();
    if (!repoPath) return;
    try {
      const diff = await getGitDiff(repoPath, diffView === 'staged');
      store.setState((s) => ({ ...s, diff }));
    } catch (err) {
      store.setState((s) => ({
        ...s,
        error: err instanceof Error ? err.message : String(err),
      }));
    }
  }

  async function stageAll(): Promise<void> {
    const { repoPath } = store.getState();
    if (!repoPath) return;
    store.setState((s) => ({ ...s, staging: true }));
    try {
      await stageGitFiles(repoPath);
      await loadRepoState(repoPath);
    } catch (err) {
      store.setState((s) => ({
        ...s,
        staging: false,
        error: err instanceof Error ? err.message : String(err),
      }));
    }
    store.setState((s) => ({ ...s, staging: false }));
  }

  async function unstageAll(): Promise<void> {
    const { repoPath } = store.getState();
    if (!repoPath) return;
    store.setState((s) => ({ ...s, staging: true }));
    try {
      await unstageGitFiles(repoPath);
      await loadRepoState(repoPath);
    } catch (err) {
      store.setState((s) => ({
        ...s,
        staging: false,
        error: err instanceof Error ? err.message : String(err),
      }));
    }
    store.setState((s) => ({ ...s, staging: false }));
  }

  async function commit(): Promise<void> {
    const { repoPath, commitMessage, unsafeOverrideReason: reason } = store.getState();
    if (!repoPath || !commitMessage.trim()) return;
    store.setState((s) => ({ ...s, committing: true, error: null, checkFailed: false }));
    try {
      const override = reason.trim() ? { reason: reason.trim() } : undefined;
      const response = await commitGit(repoPath, commitMessage, override);
      
      // Check if pre-action checks failed
      if (response.requiresOverride) {
        store.setState((s) => ({ 
          ...s,
          committing: false, 
          checkFailed: true, 
          checkResults: response.checkResults || null,
          showOverrideInput: true,
        }));
        return;
      }
      
      store.setState((s) => ({ 
        ...s,
        commitMessage: '', 
        committing: false, 
        checkResults: response.checkResults || null,
        checkFailed: false,
        unsafeOverrideReason: '',
        showOverrideInput: false,
      }));
      await loadRepoState(repoPath);
    } catch (e: any) {
      store.setState((s) => ({
        ...s,
        error: e?.message || 'Commit failed',
        committing: false,
      }));
    }
  }

  async function pull(): Promise<void> {
    const { repoPath } = store.getState();
    if (!repoPath) return;
    store.setState((s) => ({ ...s, syncing: true, error: null }));
    try {
      await pullGit(repoPath);
      await loadRepoState(repoPath);
    } catch (err) {
      store.setState((s) => ({
        ...s,
        error: err instanceof Error ? err.message : String(err),
      }));
    } finally {
      store.setState((s) => ({ ...s, syncing: false }));
    }
  }

  async function push(): Promise<void> {
    const { repoPath, unsafeOverrideReason: reason } = store.getState();
    if (!repoPath) return;
    store.setState((s) => ({ ...s, syncing: true, error: null, checkFailed: false }));
    try {
      const override = reason.trim() ? { reason: reason.trim() } : undefined;
      const response = await pushGit(repoPath, false, override);
      
      if (response.requiresOverride) {
        store.setState((s) => ({ 
          ...s,
          syncing: false, 
          checkFailed: true, 
          checkResults: response.checkResults || null,
          showOverrideInput: true,
        }));
        return;
      }
      
      store.setState((s) => ({ 
        ...s,
        syncing: false, 
        checkResults: response.checkResults || null,
        checkFailed: false,
        unsafeOverrideReason: '',
        showOverrideInput: false,
      }));
      await loadRepoState(repoPath);
    } catch (e: any) {
      store.setState((s) => ({
        ...s,
        error: e?.message || 'Push failed',
        syncing: false,
      }));
    }
  }

  async function switchBranch(options?: { create?: boolean }): Promise<void> {
    const { repoPath, selectedBranch, newBranchName } = store.getState();
    if (!repoPath) return;

    const create = Boolean(options?.create);
    const branchName = create ? newBranchName.trim() : selectedBranch.trim();
    if (!branchName) return;

    store.setState((s) => ({ ...s, switchingBranch: true, error: null }));
    try {
      await checkoutGitBranch(repoPath, { branchName, create });
      store.setState((s) => ({ ...s, newBranchName: '' }));
      await loadRepoState(repoPath);
    } catch (err) {
      store.setState((s) => ({
        ...s,
        error: err instanceof Error ? err.message : String(err),
      }));
    } finally {
      store.setState((s) => ({ ...s, switchingBranch: false }));
    }
  }

  async function createPullRequest(): Promise<void> {
    const { repoPath, pullRequestTitle, pullRequestBody } = store.getState();
    if (!repoPath) return;

    store.setState((s) => ({ ...s, creatingPullRequest: true, error: null }));
    try {
      await createGitPullRequest(repoPath, pullRequestTitle.trim(), pullRequestBody.trim());
      store.setState((s) => ({ ...s, pullRequestTitle: '', pullRequestBody: '' }));
      await loadRepoState(repoPath);
    } catch (err) {
      store.setState((s) => ({
        ...s,
        error: err instanceof Error ? err.message : String(err),
      }));
    } finally {
      store.setState((s) => ({ ...s, creatingPullRequest: false }));
    }
  }

  function setCommitMessage(commitMessage: string): void {
    store.setState((s) => ({ ...s, commitMessage, generatedBy: null }));
  }

  async function generateCommitMessage(): Promise<void> {
    const { repoPath, commitMessage: currentMessage } = store.getState();
    if (!repoPath) return;

    // NOTE: Caller (UI) must gate non-empty overwrites via confirm dialog.
    // This store action unconditionally sets the generated message.

    store.setState((s) => ({ ...s, generating: true, error: null, generateError: null, generateErrorCode: null }));
    try {
      const response = await generateCommitMessageApi(repoPath);

      if (response.ok) {
        store.setState((s) => ({
          ...s,
          commitMessage: response.message,
          generating: false,
          generatedBy: response.model,
          generateError: null,
          generateErrorCode: null,
        }));
      } else {
        store.setState((s) => ({
          ...s,
          generating: false,
          error: response.message || 'No message generated',
          generateError: response.message || response.lastError || 'Unknown error',
          generateErrorCode: response.code || null,
        }));
      }
    } catch (e: any) {
      store.setState((s) => ({
        ...s,
        generating: false,
        error: e?.message || 'Failed to generate commit message',
        generateError: e?.message || 'Failed to generate commit message',
        generateErrorCode: 'EXCEPTION',
      }));
    }
  }

  function setDiffView(diffView: 'unstaged' | 'staged'): void {
    store.setState((s) => ({ ...s, diffView, diff: null }));
  }

  function setSelectedBranch(selectedBranch: string): void {
    store.setState((s) => ({ ...s, selectedBranch }));
  }

  function setNewBranchName(newBranchName: string): void {
    store.setState((s) => ({ ...s, newBranchName }));
  }

  function setPullRequestTitle(pullRequestTitle: string): void {
    store.setState((s) => ({ ...s, pullRequestTitle }));
  }

  function setPullRequestBody(pullRequestBody: string): void {
    store.setState((s) => ({ ...s, pullRequestBody }));
  }

  function setUnsafeOverrideReason(reason: string): void {
    store.setState((s) => ({ ...s, unsafeOverrideReason: reason }));
  }

  function clearCheckState(): void {
    store.setState((s) => ({ ...s, checkFailed: false, checkResults: null, showOverrideInput: false, unsafeOverrideReason: '' }));
  }

  function clearGenerateError(): void {
    store.setState((s) => ({ ...s, generateError: null, generateErrorCode: null }));
  }

  function reset(): void {
    requestVersion++;
    store.setState(INITIAL_STATE);
  }

  return {
    getState: store.getState,
    subscribe: store.subscribe,
    loadStatus,
    loadDiff,
    stageAll,
    unstageAll,
    commit,
    pull,
    push,
    switchBranch,
    createPullRequest,
    setCommitMessage,
    generateCommitMessage,
    setDiffView,
    setSelectedBranch,
    setNewBranchName,
    setPullRequestTitle,
    setPullRequestBody,
    setUnsafeOverrideReason,
    clearCheckState,
    clearGenerateError,
    reset,
  };
}

export const gitStore = createGitStore();
